[package]
name = "leftcenterright"
version = "0.1.0"
authors = ["Warren Weckesser <warren.weckesser@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
rand = "0.8"
